# Generated by Django 5.0 on 2023-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
